// <auto-generated />
namespace FluffyCRM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class clientstuff21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clientstuff21));
        
        string IMigrationMetadata.Id
        {
            get { return "201703252131587_clientstuff21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
